[tool.poetry]
name = "echoserver"
version = "0.1.0"
description = ""
authors = ["Kavi Laud <kavinath@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
trio = "^0.20.0"
hypercorn = "^0.13.2"
starlette = "^0.19.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
flake8-bugbear = "^22.3.23"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
